-- ══════════════════════════════════════════════════════════════
-- SNOWFLAKE ENGINEERING WORKBOOK
-- Author  : Marc Bacchus · github.com/marcbacchus/data-engineering-workbooks
-- Goal 4  : Secure Your Environment
-- Sub-task 4.10 : Exam prep — Data Governance and Security
-- ──────────────────────────────────────────────────────────────
-- Time to complete : ~30 minutes
-- Warehouse size   : X-Small (WORKBOOK_WH)
-- Database         : ECOMMERCE
-- Run in           : Snowsight
-- Prerequisites    : Sub-tasks 4.1-4.9 complete
-- COF-C03 domain   : Domain 4 — Data Governance and Security (23%)
-- ══════════════════════════════════════════════════════════════
--
-- WHAT YOU ARE DOING AND WHY
--   15 practice questions covering everything built in Goal 4,
--   in the style and weighting of COF-C03's Domain 4 (Data
--   Governance and Security, 23% of the exam — the single
--   largest domain). Each question includes the answer, why it's
--   correct, why every other option is wrong, and which sub-task
--   to revisit if you got it wrong.
--
-- ══════════════════════════════════════════════════════════════
-- QUESTIONS
-- ══════════════════════════════════════════════════════════════

-- Q1. You need to create a new database and warehouse for a
-- project. Which system role is the correct daily-driver choice
-- for this kind of work?
--
-- A) ACCOUNTADMIN
-- B) SECURITYADMIN
-- C) SYSADMIN
-- D) USERADMIN
--
-- Answer: C
--
-- Explanation:
--   SYSADMIN creates warehouses, databases, and other objects,
--   and is the role meant to own and build day-to-day working
--   objects — the intended daily-driver role for this kind of
--   task.
--
-- Why the others are wrong:
--   A) ACCOUNTADMIN combines SYSADMIN and SECURITYADMIN and
--      technically CAN create these objects, but should never be
--      a daily-driver role — its blast radius is the entire
--      account.
--   B) SECURITYADMIN manages users, roles, and grants
--      account-wide, but has no privilege to create warehouses or
--      databases on its own.
--   D) USERADMIN can create and manage users and roles, but
--      cannot grant privileges on objects like warehouses or
--      databases, and has no CREATE WAREHOUSE/DATABASE privilege
--      by default.
--
-- Review: Sub-task 4.1 — CONCEPT section, system roles

-- ─────────────────────────────────────────────────────────────

-- Q2. A role has been granted SELECT on a table directly, but a
-- query against that table still fails with an authorization
-- error. Assuming the privilege was granted correctly, what is
-- the MOST likely missing piece?
--
-- A) The role also needs OWNERSHIP on the table
-- B) The role is missing USAGE on the table's database and/or
--    schema
-- C) The table needs to be re-created with GRANT OPTION
-- D) The role needs to be granted to PUBLIC first
--
-- Answer: B
--
-- Explanation:
--   Querying a table requires USAGE on its database AND USAGE on
--   its schema, in addition to the object-level privilege
--   (SELECT) — three separate grants, not one. Missing either
--   container-level USAGE grant produces exactly this symptom:
--   correct table-level privilege, query still fails.
--
-- Why the others are wrong:
--   A) OWNERSHIP controls who can alter or drop an object — it is
--      not required to query it, and granting it here would be
--      both unnecessary and far too broad.
--   C) GRANT OPTION lets the grantee re-grant a privilege to
--      other roles; it has no effect on whether the original
--      grantee can query the object.
--   D) Granting the role to PUBLIC would expose the table
--      account-wide instead of fixing the one role's missing
--      grant — a serious overcorrection, not a fix.
--
-- Review: Sub-task 4.1 — Step 6

-- ─────────────────────────────────────────────────────────────

-- Q3. You switch your session to a narrower role using USE ROLE
-- ANALYST_ROLE specifically to test what that role alone can
-- access. The test query unexpectedly succeeds even though
-- ANALYST_ROLE was never granted access to the object queried.
-- What is the most likely explanation?
--
-- A) ANALYST_ROLE inherited access through a masking policy
-- B) The account's DEFAULT_SECONDARY_ROLES setting is ALL, and a
--    different role your user holds still has access
-- C) USE ROLE does not take effect until the session restarts
-- D) PUBLIC was granted access to every object by default
--
-- Answer: B
--
-- Explanation:
--   With DEFAULT_SECONDARY_ROLES = ALL (the Snowflake default per
--   BCR-1692), a session aggregates privileges from every role
--   the user holds, not just the active primary role. USE ROLE
--   alone does not isolate a role's true privileges —
--   USE SECONDARY ROLES NONE is required to test a role in true
--   isolation.
--
-- Why the others are wrong:
--   A) Masking policies control the VALUE returned in a column,
--      not whether an object can be accessed at all — they
--      cannot explain a query succeeding against an object with
--      no grant.
--   C) USE ROLE takes effect immediately for the current session;
--      no restart is needed.
--   D) A fresh account grants PUBLIC almost nothing beyond
--      Snowflake's own baseline system objects — it is not
--      granted broad access by default.
--
-- Review: Sub-task 4.1 — CONCEPT (secondary roles) and Step 5

-- ─────────────────────────────────────────────────────────────

-- Q4. In Snowflake's recommended custom role pattern, which
-- statement correctly describes the difference between an access
-- role and a functional role?
--
-- A) An access role is granted directly to users; a functional
--    role is granted only to other roles
-- B) A functional role holds object privileges; an access role
--    holds only other roles
-- C) An access role holds object privileges and is never granted
--    directly to a user; a functional role holds access roles and
--    IS granted to users
-- D) There is no meaningful difference — both terms describe the
--    same kind of role
--
-- Answer: C
--
-- Explanation:
--   Access roles hold object privileges (USAGE, SELECT, etc.) and
--   are never granted directly to a user. Functional roles hold
--   no privileges of their own — they hold one or more access
--   roles, and ARE granted to users. This split is Snowflake's
--   documented, exam-tested convention.
--
-- Why the others are wrong:
--   A) This reverses the pattern — access roles are specifically
--      the ones that should NEVER be granted directly to a user;
--      functional roles are what gets granted to users.
--   B) Also reversed — functional roles hold no privileges of
--      their own at all; access roles are the ones that hold
--      privileges.
--   D) The distinction is real, documented, and tested — mixing
--      privileges and user-facing identity into one flat role
--      works technically but becomes hard to audit as it grows.
--
-- Review: Sub-task 4.2 — CONCEPT

-- ─────────────────────────────────────────────────────────────

-- Q5. A role was granted ALL PRIVILEGES on a table. Which
-- privilege is guaranteed to be EXCLUDED from that grant?
--
-- A) SELECT
-- B) REFERENCES
-- C) OWNERSHIP
-- D) TRUNCATE
--
-- Answer: C
--
-- Explanation:
--   ALL PRIVILEGES is a pseudo-privilege that expands to every
--   applicable privilege for the object type EXCEPT OWNERSHIP,
--   which must always be transferred explicitly with
--   GRANT OWNERSHIP.
--
-- Why the others are wrong:
--   A) SELECT is one of the ordinary table privileges included in
--      ALL PRIVILEGES.
--   B) REFERENCES is also included.
--   D) TRUNCATE is also included.
--
-- Review: Sub-task 4.3 — CONCEPT, Practice Gap exercise 3

-- ─────────────────────────────────────────────────────────────

-- Q6. ROLE_A was granted SELECT WITH GRANT OPTION on a table, and
-- used that option to re-grant SELECT to ROLE_B. An administrator
-- now runs REVOKE SELECT ... FROM ROLE_A, with no additional
-- keywords. What happens?
--
-- A) ROLE_A loses SELECT; ROLE_B keeps its re-granted SELECT, now
--    orphaned
-- B) The REVOKE fails outright — 0 grants revoked — because
--    ROLE_B's dependent grant exists and CASCADE was not
--    specified
-- C) Both ROLE_A and ROLE_B immediately lose SELECT
-- D) The REVOKE succeeds, but only takes effect after ROLE_B's
--    session ends
--
-- Answer: B
--
-- Explanation:
--   Snowflake will not partially apply a REVOKE when dependent
--   grants exist. The statement fails outright — nothing changes,
--   not even the original grant — and returns an error naming the
--   dependent grant. CASCADE must be added to revoke the original
--   grant and every dependent grant it enabled, together, in one
--   statement.
--
-- Why the others are wrong:
--   A) This is the common, intuitive assumption — but it is not
--      what actually happens. Snowflake blocks the whole
--      operation rather than leaving an orphaned grant behind.
--   C) Without CASCADE, neither role loses access — the REVOKE
--      does not execute at all.
--   D) There is no session-based delay for grant/revoke
--      operations in Snowflake — they are immediate or blocked,
--      never queued.
--
-- Review: Sub-task 4.3 — Step 3

-- ─────────────────────────────────────────────────────────────

-- Q7. A schema has a future grant of SELECT on future tables at
-- the DATABASE level. A more specific future grant of SELECT on
-- future tables is then added at the SCHEMA level for one
-- particular schema, with different privileges. A new table is
-- created in that schema. Which future grant applies to it?
--
-- A) Both future grants apply and are merged together
-- B) The database-level future grant always takes precedence
-- C) The schema-level future grant takes precedence; the
--    database-level one is ignored for that schema
-- D) Neither applies — future grants never apply to tables
--    created after the fact
--
-- Answer: C
--
-- Explanation:
--   When future grants exist at both the database level and the
--   schema level for the same object type, the schema-level
--   future grant wins and the database-level one is ignored for
--   that schema — a real gotcha, since a broad database-level
--   future grant can be silently overridden by a narrower
--   schema-level one nobody remembers setting.
--
-- Why the others are wrong:
--   A) Snowflake does not merge future grants from different
--      levels — only one applies.
--   B) This is the opposite of the actual precedence rule — the
--      more specific, schema-level grant wins.
--   D) Future grants exist specifically to apply automatically to
--      objects created after the grant is issued — that is their
--      entire purpose.
--
-- Review: Sub-task 4.3 — CONCEPT, Step 5

-- ─────────────────────────────────────────────────────────────

-- Q8. SYSADMIN owns a database but attempts to run a
-- GRANT ... ON FUTURE TABLES statement against it, and the
-- statement fails with an insufficient-privileges error
-- referencing MANAGE GRANTS. What is the correct fix?
--
-- A) Grant OWNERSHIP on the database to SYSADMIN again
-- B) Switch to a role that holds MANAGE GRANTS (ACCOUNTADMIN or
--    SECURITYADMIN by default) to run that specific statement
-- C) Add WITH GRANT OPTION to the future grant statement
-- D) Future grants can only ever be run by the object's creator,
--    regardless of role
--
-- Answer: B
--
-- Explanation:
--   GRANT/REVOKE ... ON FUTURE ... requires the global MANAGE
--   GRANTS privilege, held only by ACCOUNTADMIN and SECURITYADMIN
--   by default — regardless of what the requesting role owns.
--   SYSADMIN, even as the database's owner, cannot run this
--   statement without that separate privilege.
--
-- Why the others are wrong:
--   A) SYSADMIN already owns the database in this scenario —
--      re-granting ownership to itself changes nothing and does
--      not address the missing MANAGE GRANTS privilege.
--   C) WITH GRANT OPTION controls whether the GRANTEE can
--      re-grant a privilege to others; it has no bearing on
--      whether the GRANTOR is authorized to issue a future grant
--      in the first place.
--   D) Future grants are not restricted to an object's original
--      creator — they are gated by the MANAGE GRANTS privilege,
--      which can be granted to other roles.
--
-- Review: Sub-task 4.3 — CONCEPT, Steps 4-5

-- ─────────────────────────────────────────────────────────────

-- Q9. Which privilege must be explicitly granted to a custom role
-- before that role can attach (not just author) a masking policy
-- to a table column?
--
-- A) CREATE MASKING POLICY
-- B) APPLY MASKING POLICY
-- C) OWNERSHIP on the table
-- D) USAGE on the masking policy
--
-- Answer: B
--
-- Explanation:
--   APPLY MASKING POLICY is the account-level (global) privilege
--   required to attach a masking policy to a column. It is held
--   only by ACCOUNTADMIN by default and must be explicitly
--   granted to any other role.
--
-- Why the others are wrong:
--   A) CREATE MASKING POLICY only allows a role to author policy
--      objects — it says nothing about whether that role can
--      attach a policy to a column.
--   C) Owning the table does not grant the ability to attach a
--      masking policy — attachment is governed entirely by the
--      separate APPLY MASKING POLICY privilege.
--   D) There is no "USAGE on a masking policy" privilege that
--      governs attachment — APPLY is the specific privilege type
--      required.
--
-- Review: Sub-task 4.4 — CONCEPT, Step 1

-- ─────────────────────────────────────────────────────────────

-- Q10. A masking policy, a row access policy, and a network rule
-- are each already attached/referenced somewhere. In each case,
-- what happens if you run CREATE OR REPLACE against the object
-- itself?
--
-- A) All three succeed silently, updating the logic in place
-- B) All three fail outright, since the object is already in use
--    elsewhere — ALTER ... SET ... must be used instead
-- C) Only the network rule fails; the two policy types allow
--    CREATE OR REPLACE while attached
-- D) All three require the object to be renamed first
--
-- Answer: B
--
-- Explanation:
--   All three object types share the same lifecycle restriction:
--   CREATE OR REPLACE only works before the object is attached to
--   anything. Once attached — a column, a table, or a network
--   policy's allow/block list — CREATE OR REPLACE (and DROP) fail
--   outright, and ALTER ... SET BODY / ALTER ... SET VALUE_LIST
--   must be used to update the object in place instead.
--
-- Why the others are wrong:
--   A) This is the opposite of the actual behavior — none of the
--      three succeed once attached; all three fail.
--   C) The restriction applies equally to all three object types
--      — the network rule is not a special case, and neither
--      policy type is exempt.
--   D) Renaming the object has no bearing on this restriction and
--      is not part of the fix.
--
-- Review: Sub-tasks 4.4/4.5 Step 7, Sub-task 4.7

-- ─────────────────────────────────────────────────────────────

-- Q11. A row access policy's body includes a subquery against a
-- mapping table to look up which roles are allowed to see which
-- region. The querying role has never been granted SELECT on that
-- mapping table. What happens when a mapped role runs a query
-- against the protected table?
--
-- A) The query fails — the querying role needs SELECT on the
--    mapping table
-- B) The query succeeds — the policy body executes with the
--    PRIVILEGES OF THE POLICY OWNER, not the querying role
-- C) The query succeeds only if the querying role also holds
--    SECURITYADMIN
-- D) Row access policies cannot reference other tables at all
--
-- Answer: B
--
-- Explanation:
--   Mapping table lookups inside a row access policy body execute
--   with the privileges of whoever OWNS the policy, not the
--   querying role. The querying role never needs its own grant on
--   the mapping table — this is a deliberate design choice that
--   avoids exposing the mapping table to every role the policy
--   protects.
--
-- Why the others are wrong:
--   A) This is the common, incorrect assumption about how the
--      lookup works — the querying role's own privileges on the
--      mapping table are irrelevant to whether the policy
--      evaluates successfully.
--   C) SECURITYADMIN has no special role in row access policy
--      evaluation — the policy OWNER's privileges are what
--      matter, regardless of which system role that happens to
--      be.
--   D) Referencing other tables via a subquery — the mapping
--      table pattern — is one of the most common and fully
--      supported row access policy designs.
--
-- Review: Sub-task 4.5 — CONCEPT

-- ─────────────────────────────────────────────────────────────

-- Q12. What is the primary advantage of binding a masking policy
-- to a TAG rather than attaching it directly to each column with
-- ALTER TABLE ... SET MASKING POLICY?
--
-- A) Tag-based masking evaluates faster at query time
-- B) Protecting a new or existing column of a matching data type
--    only requires tagging it — no new ALTER TABLE ... SET
--    MASKING POLICY statement is needed for that column
-- C) Tags allow a masking policy to bypass row access policies
-- D) Tag-based masking does not require the APPLY MASKING POLICY
--    privilege
--
-- Answer: B
--
-- Explanation:
--   Once a masking policy is bound to a tag, applying that tag to
--   any column of a matching data type automatically applies the
--   masking — no separate ALTER TABLE ... SET MASKING POLICY
--   statement is needed for that column, existing or brand new.
--   This directly addresses masking's lack of a future-grant
--   equivalent.
--
-- Why the others are wrong:
--   A) There is no documented performance advantage to tag-based
--      masking over direct attachment — the benefit is
--      administrative and scalability-related, not speed.
--   C) Tags do not bypass row access policies. Both mechanisms
--      evaluate completely independently, and row access still
--      applies to a tagged column exactly as it would otherwise.
--   D) Binding a masking policy to a tag still requires APPLY
--      MASKING POLICY (to bind the policy to the tag) and
--      separately APPLY TAG (to apply the tag to a column) — the
--      privilege requirement is not eliminated, just reused.
--
-- Review: Sub-task 4.6 — CONCEPT, Step 7

-- ─────────────────────────────────────────────────────────────

-- Q13. A network policy's ALLOWED_NETWORK_RULE_LIST includes a
-- rule allowing a single specific IP address. Its
-- BLOCKED_NETWORK_RULE_LIST includes a separate rule covering
-- 0.0.0.0/0 (every IPv4 address). What happens when that specific
-- allowed IP attempts to connect?
--
-- A) It is allowed, since the allow rule is more specific
-- B) It is blocked — when an IP matches both lists, the blocked
--    list always wins, regardless of specificity
-- C) Snowflake rejects the policy at creation time as invalid
-- D) The most recently created rule always takes precedence
--
-- Answer: B
--
-- Explanation:
--   When an IP matches both the allowed and blocked lists, the
--   blocked list always wins — even if the allowed entry is far
--   more specific than the blocked one. Snowflake does not do
--   longest-prefix-match the way network routing does.
--
-- Why the others are wrong:
--   A) This is the intuitive but incorrect assumption — greater
--      specificity does not override the blocked list in
--      Snowflake's evaluation order.
--   C) Snowflake does not validate for this kind of logical
--      conflict at creation time — the policy is created
--      successfully, and the precedence rule only becomes visible
--      at connection/evaluation time.
--   D) There is no recency-based precedence rule — the blocked
--      list wins regardless of which rule was created first or
--      most recently.
--
-- Review: Sub-task 4.7 — CONCEPT, Practice Gap exercise 4

-- ─────────────────────────────────────────────────────────────

-- Q14. A role has never been granted SELECT (or any privilege) on
-- a base table. That role IS granted SELECT on a secure view
-- built on top of that table. Can the role successfully query the
-- view?
--
-- A) No — a role always needs privileges on the underlying base
--    table(s) as well
-- B) Yes — views (secure or not) execute with the OWNER's
--    privileges on the base tables, so the querying role only
--    needs SELECT on the view itself
-- C) Only if the view is NOT secure
-- D) Only if the role also holds ACCOUNTADMIN
--
-- Answer: B
--
-- Explanation:
--   Any view — secure or not — runs with the OWNER's privileges
--   on the underlying tables, not the querying role's. A role
--   only needs SELECT on the view itself; it never needs SELECT
--   on the base table directly. This is the single most useful
--   property of views as a security mechanism.
--
-- Why the others are wrong:
--   A) This is the common misconception this question is testing
--      — the querying role does NOT need base table privileges;
--      the view owner's privileges are what get used.
--   C) Owner's-rights behavior applies to both secure and
--      non-secure views equally. SECURE only adds hidden-
--      definition protection and disables certain query-plan
--      optimizations — it does not change the privilege model.
--   D) ACCOUNTADMIN plays no special role here — any role granted
--      SELECT on the view benefits from owner's rights, regardless
--      of what other roles it holds.
--
-- Review: Sub-task 4.8 — CONCEPT, Step 7

-- ─────────────────────────────────────────────────────────────

-- Q15. ROLE_B has been granted into ROLE_A's hierarchy
-- (GRANT ROLE ROLE_B TO ROLE ROLE_A). A masking policy's body
-- reads:
--   CASE WHEN CURRENT_ROLE() IN ('ROLE_B') THEN val ELSE '***' END
-- A user whose ACTIVE PRIMARY role is ROLE_A queries the protected
-- column. What do they see?
--
-- A) The real value — ROLE_A inherited ROLE_B's access through the
--    hierarchy
-- B) The masked value — CURRENT_ROLE() returns 'ROLE_A', not
--    'ROLE_B', regardless of the hierarchy grant
-- C) An error — Snowflake disallows granting a role referenced
--    inside a masking policy to any other role
-- D) It depends on whether secondary roles are enabled
--
-- Answer: B
--
-- Explanation:
--   CURRENT_ROLE() reflects only the literal active primary role
--   — never a role inherited through hierarchy. ROLE_A inherits
--   ROLE_B's PRIVILEGES through the GRANT ROLE ... TO ROLE
--   hierarchy, but CURRENT_ROLE() still returns 'ROLE_A' when
--   ROLE_A is active, so the policy's CASE condition never
--   matches. IS_ROLE_IN_SESSION('ROLE_B') would return TRUE here
--   and is the correct function to use if hierarchy-aware masking
--   is the intended design.
--
-- Why the others are wrong:
--   A) This is the exact misconception this question — and the
--      Sub-task 4.9 capstone — is built to correct. Inheriting a
--      role's privileges through hierarchy does not change what
--      CURRENT_ROLE() returns.
--   C) Snowflake places no such restriction — a role referenced
--      inside a masking policy can be freely granted into another
--      role's hierarchy with no error at all.
--   D) This scenario is about PRIMARY role hierarchy, not
--      secondary roles. Even with secondary roles fully enabled,
--      CURRENT_ROLE() still only reflects the literal active
--      primary role — secondary roles being on or off doesn't
--      change this outcome.
--
-- Review: Sub-task 4.9 — CONCEPT, Steps 1-6

-- ══════════════════════════════════════════════════════════════
-- SCORING GUIDE
-- ══════════════════════════════════════════════════════════════
--
--   13-15 correct : Strong command of Domain 4. Ready to move on.
--   10-12 correct : Solid, but revisit the specific sub-tasks
--                   behind any missed questions before moving on.
--   Below 10      : Worth re-running the hands-on steps for the
--                   sub-tasks behind your missed questions —
--                   this workbook is built so every concept here
--                   was something you actually did, not just read.
-- ══════════════════════════════════════════════════════════════
